Repository SWYP-Playground/Playground-Back, pull requests merged in 2024-11, with the labels that each got.

#1 feat:구조 생성
  build.gradle
  src/main/java/com/swyp/playground/common/jwt/JwtAuthFilter.java
  src/main/java/com/swyp/playground/common/jwt/JwtTokenProvider.java
  src/main/java/com/swyp/playground/common/redis/RedisService.java
  src/main/java/com/swyp/playground/common/response/CommonResponse.java
  src/main/java/com/swyp/playground/common/response/ExceptionResponse.java
  src/main/java/com/swyp/playground/domain/parent/domain/Parent.java
  src/main/java/com/swyp/playground/domain/parent/repository/ParentRepository.java
Labels: feat

#2 docker추가
  Dockerfile
Labels: feat

#3 Structure dockeradd v1
  Dockerfile
Labels: 긴급

#4 bind mount방식으로 코드 수정시 빠르게 확인 가능
  Dockerfile
  src/main/java/com/swyp/playground/domain/parent/controller/ParentController.java
  src/main/java/com/swyp/playground/domain/parent/domain/Parent.java
Labels: 긴급

#5 add
  Dockerfile
  build.gradle
  src/main/java/com/swyp/playground/domain/parent/controller/ParentController.java
Labels: 긴급

#8 feat:parent,child컬럼 추가 및 회원가입 기능 구현
  build.gradle
  src/main/java/com/swyp/playground/common/config/SecurityConfig.java
  src/main/java/com/swyp/playground/common/domain/TypeChange.java
  src/main/java/com/swyp/playground/domain/child/controller/ChildController.java
  src/main/java/com/swyp/playground/domain/child/domain/Child.java
  src/main/java/com/swyp/playground/domain/child/domain/ChildGenderType.java
  src/main/java/com/swyp/playground/domain/child/repository/ChildRepository.java
  src/main/java/com/swyp/playground/domain/child/service/ChildService.java
  src/main/java/com/swyp/playground/domain/parent/controller/ParentController.java
  src/main/java/com/swyp/playground/domain/parent/domain/Parent.java
  src/main/java/com/swyp/playground/domain/parent/domain/ParentRoleType.java
  src/main/java/com/swyp/playground/domain/parent/dto/req/ParentCreateReqDto.java
  src/main/java/com/swyp/playground/domain/parent/dto/res/ParentCreateResDto.java
  src/main/java/com/swyp/playground/domain/parent/service/ParentService.java
Labels: feat

#11 Feature/find friend
  build.gradle
  src/main/java/com/swyp/playground/common/config/SecurityConfig.java
  src/main/java/com/swyp/playground/domain/child/domain/Child.java
  src/main/java/com/swyp/playground/domain/findfriend/controller/FindFriendController.java
  src/main/java/com/swyp/playground/domain/findfriend/domain/FindFriend.java
  src/main/java/com/swyp/playground/domain/findfriend/dto/FindFriendInfoResponse.java
  src/main/java/com/swyp/playground/domain/findfriend/dto/FindFriendListResponse.java
  src/main/java/com/swyp/playground/domain/findfriend/dto/FindFriendRegisterRequest.java
  src/main/java/com/swyp/playground/domain/findfriend/repository/FindFriendRepository.java
  src/main/java/com/swyp/playground/domain/findfriend/service/FindFriendService.java
  src/main/java/com/swyp/playground/domain/playground/controller/playgroundController.java
  src/main/java/com/swyp/playground/domain/playground/dto/PlaygroundInfoResponse.java
  src/main/java/com/swyp/playground/domain/playground/service/PlaygroundService.java
Labels: feat

#12 Oauth/user v1
  build.gradle
  src/main/java/com/swyp/playground/common/config/SecurityConfig.java
  src/main/java/com/swyp/playground/common/config/SwaggerConfig.java
  src/main/java/com/swyp/playground/common/domain/TypeChange.java
  src/main/java/com/swyp/playground/common/jwt/JwtAuthFilter.java
  src/main/java/com/swyp/playground/common/jwt/JwtTokenProvider.java
  src/main/java/com/swyp/playground/common/response/CommonResponse.java
  src/main/java/com/swyp/playground/domain/login/controller/LoginController.java
  src/main/java/com/swyp/playground/domain/parent/controller/ParentController.java
  src/main/java/com/swyp/playground/domain/parent/dto/res/ParentCreateResDto.java
  src/main/java/com/swyp/playground/domain/parent/repository/ParentRepository.java
  src/main/java/com/swyp/playground/domain/parent/service/ParentService.java
Labels: refactor, feat

#15 feat:smtp 메일 전송
  build.gradle
  src/main/java/com/swyp/playground/common/config/SecurityConfig.java
  src/main/java/com/swyp/playground/domain/email/config/EmailConfig.java
  src/main/java/com/swyp/playground/domain/email/controller/EmailController.java
  src/main/java/com/swyp/playground/domain/email/dto/req/EmailReqDto.java
  src/main/java/com/swyp/playground/domain/email/service/EmailService.java
  src/main/java/com/swyp/playground/domain/email/service/EmailServiceImpl.java
Labels: feat
